name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for opening an issue! Wait for the maintainer to get assigned before making a pull request."
        pr-message: "Thanks for your amazing contribution! Our maintainers will review your PR soon :)"
